### PR TITLE
Ensure compatibility with Twig 3

### PR DESCRIPTION
**Pull request by relthyg**
The classes `\Twig_Extension` and `\Twig_SimpleFunction` have been removed in Twig 3 in favor of `Twig\Extension\AbstractExtension` and `Twig\TwigFunction` respectively. As these classes were only introduced in Twig 2.4.0, we have to drop support for older Twig versions here.

Silex support is dropped because the `CalendRServiceProviderTest` fails now without the `\Twig_Extension` class. As Silex is not maintained anymore, it should not be a problem to drop it's support. This should be considered as a BC-break.

### CODE REVIEW

**Comment by peter279k** [comment]
Due to the BC-break, I think we consider releasing the `3.2.0` version.

What do you think about that?

**Comment by relthyg** [comment]
If you want to follow [Sem er](https://semver.org), this would be a 4.0.0.

**Comment by relthyg** [comment]
Is anything still unclear here that I could help with?

**Comment by peter279k** [comment]
I've merged this PR and prepare to release the `4.0.0` version.

**Comment by relthyg** [comment]
Great, thank you

**Comment by relthyg** [comment]
Hey, it's been a while. Are you still planning to release version `4.0.0`? Can I help with something?

**Comment by peter279k** [comment]
The `4.0.0` is released and sorry for my delay response.

https://github.com/peter279k/fork-CalendR/releases/tag/4.0.0

**Comment by relthyg** [comment]
Thank you!

**Pull request merged**
