### PR TITLE
Allow Symfony 6 components

### PR DESCRIPTION
**Pull request by relthyg**

### CODE REVIEW

**Comment by peter279k** [comment]
Thanks for your contribution :).

**Comment by relthyg** [comment]
That was quick :-) Would you mind tagging a new release?

**Comment by peter279k** [comment]
I will create the new release later :).

**Comment by relthyg** [comment]
Thank you!

**Comment by peter279k** [comment]
The new released version is created now :).
https://github.com/peter279k/fork-CalendR/releases/tag/3.1.2

**Comment by relthyg** [comment]
Thanks a lot!

**Pull request merged**
